version : '3'

services :
  mariadb :
    build : ./requirements/mariadb/
    image : mariadb
    container_name: mariadb
    restart : always
    env_file :
      - .env
    expose :
      - "3306"
    networks :
      - inception_sub
    volumes :
      - db:/var/lib/mariadb
  wordpress :
    build : ./requirements/wordpress/
    container_name: wordpress
    image : wordpress
    env_file :
      - .env
    restart : always
    depends_on :
      - mariadb
    expose :
      - "9000"
    networks :
      - inception_sub
    volumes :
      - wp:/var/www/html
  nginx :
    build : ./requirements/nginx/
    container_name: nginx
    image : nginx
    restart : always
    depends_on :
      - wordpress
    ports :
      - "443:443"
    networks :
      - inception_sub
    volumes :
      - wp:/var/www/html
#볼륨은 호스트와 Docker 컨테이너간 공유폴더입니다.
#볼륨을 사용함으로써 도커 컨테이너가 꺼져도 볼륨 폴더가 살아있는 한 이전에 저장된 값들을 그대로 들고있게 됩니다.
volumes :
  db :
    driver : local
    driver_opts :
      type : none
      device : /home/jugwak/data/mariadb_v
      o : bind
  wp :
    driver : local
    driver_opts :
      type : none
      device : /home/jugwak/data/wordpress_v
      o : bind
#네트워크는 해당 네트워크를 사용하는 모든 컨테이너들은 해당 네트워크에 속하게 됩니다.
#해당 네트워크에 있는 다른 컨테이너들과 통신을 할 수 있게 해줍니다.
#bridge는 네트워크의 기본값인데 이걸 사용하면 Docker 호스트 내에서 컨테이너 간 통신이 가능해지며, 호스트 시스템의 다른 네트워크와 격리됩니다.
networks :
  inception_sub :
    driver : bridge